service: MambyLy-logistics-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  environment:
    BUCKET_BASE: ${env:S3_BUCKET_BASE}
    BUCKET_NAME: ${env:S3_BUCKET_BASE}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
        - lambda:UpdateFunctionCode
        - apiGateway:*
        - s3:*
      Resource: "*"

functions:
  test:
    handler: handlers/test/test.handler
    events:
      - http:
          path: test
          method: get
