service: MambyLy-logistics-backend

provider:
  name: aws
  runtime: nodejs18.x  
  stage: dev
  region: ${env:AWS_REGION} 

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
        - lambda:UpdateFunctionCode
        - apigateway:*
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::mambyly-uploads-${self:provider.stage}
        - arn:aws:s3:::mambyly-uploads-${self:provider.stage}/*

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mambyly-uploads-${self:provider.stage}

functions:
  test:
    handler: handlers/test/test.handler 
    events:
      - http:
          path: test 
          method: get
