service: MambyLy-logistics-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  stage: ${opt:stage, 'dev'}
  environment:
    BUCKET_NAME: ${env:S3_BUCKET_BASE}-${self:provider.stage}
    ADMIN_TABLE_NAME: ${env:ADMIN_TABLE_BASE}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:CreateFunction
        - lambda:UpdateFunctionCode
        - apiGateway:*
        - s3:*
        - dynamodb:*
      Resource: "*"

functions:
  test:
    handler: handlers/test/test.handler
    events:
      - http:
          path: test
          method: get

  functions:
  registerAdmin:
    handler: register/index.handler
    events:
      - http:
          path: admin/register
          method: post
          cors: true

resources:
  Resources:
    AdminTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ADMIN_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: adminId
            AttributeType: S
        KeySchema:
          - AttributeName: adminId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
