name: Dev Deployment

on:
  push:
    branches:
      - dev
      - feature/*

permissions:
  contents: read
  id-token: write
  actions: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_BUCKET_BASE: ${{ secrets.S3_BUCKET_BASE }}
  ADMIN_TABLE_BASE: ${{ secrets.ADMIN_TABLE_BASE }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  CLIENTS_MESSAGES_BASE: ${{ secrets.CLIENTS_MESSAGES_BASE }}
  JOB_MESSAGES_BASE: ${{ secrets.JOB_MESSAGES_BASE }}
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set BUCKET_NAME
        run: echo "BUCKET_NAME=${{ env.S3_BUCKET_BASE }}-dev" >> $GITHUB_ENV

      - name: Set ADMIN_TABLE_NAME
        run: echo "ADMIN_TABLE_NAME=${{ env.ADMIN_TABLE_BASE }}-dev" >> $GITHUB_ENV

      - name: Set JWT_SECRET_KEY
        run: echo "JWT_SECRET_KEY=${{ env.JWT_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Set CLIENTS_MESSAGES_NAME
        run: echo "CLIENTS_MESSAGES_NAME=${{ env.CLIENTS_MESSAGES_BASE }}-dev" >> $GITHUB_ENV

      - name: Set JOB_MESSAGES_NAME
        run: echo "JOB_MESSAGES_NAME=${{ env.JOB_MESSAGES_BASE }}-dev" >> $GITHUB_ENV

      - name: Deploy with Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: npx serverless deploy --stage dev --region $AWS_REGION
